# Copyright 2021 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

# app mode: debug, release
app_mode: release

# env
env: dev # dev, production

# Log level
log_level: 5  # 5 is debug level, use 4(info) in prod

# Gin http server config
http_server:
  mode: debug # or release, debug
  port: :8091

# time in second before server shutdown
# this will allow server to finish running jobs before shutdown
finish_up_time: 3

# internal scheduled cronjob
cron_job:
  update_conversion_rate_job:
    name: conversion rate
    enable: true
    check_frequency: "* * * * *"
    process_number: 1
  update_gas_price_job:
    name: gas price
    enable: true
    check_frequency: "* * * * *"
    process_number: 1

# store path
store:
  path: ./lvldbdata

oracle:
  etherscan:
    enable: true
    api_key:
    apis:
      gas_price:
    gas_price_domainIDs: [ ]
  polygonscan:
    enable: true
    api_key:
    apis:
      gas_price:
    gas_price_domainIDs: [ ]
  coinmarketcap:
    enable: true
    api_key:
    apis:
      query_rate:
    gas_price_domainIDs: [ ]

# conversion_rate_pairs contains price pair for conversion rate
# must be paired and follow the format of [ base, foreign, base, foreign, ... ]
conversion_rate_pairs:
  [ eth, usd ]

# strategy defines the strategy on verify and aggregate data from store when fetched
strategy:
  local: average

# data_valid_interval defines how long the endpoint response data remains valid before sending it to fee handler contract
data_valid_interval: 3600 # second
